// apps/web-vuejs/src/components/NavMain.vue
<script setup lang="ts">
import {
  IconDashboard,
  IconUsers,
  IconShield,
  IconLock,
  IconFileDescription,
  IconChartCandle,
} from "@tabler/icons-vue"

import {
  SidebarGroup,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
} from '@/components/ui/sidebar'
import { usePermissions } from '@/composables/usePermissions'
import { useAuthStore } from '@/stores/auth'
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { toast } from 'vue-sonner'

const { hasPermission, isAdmin } = usePermissions()
const authStore = useAuthStore()
const router = useRouter()

const navItems = computed(() => {
  const items = [
    {
      title: 'Dashboard',
      url: '/dashboard',
      icon: IconDashboard,
      visible: true,
    },
    {
      title: 'Users',
      url: '/dashboard/users',
      icon: IconUsers,
      visible: isAdmin.value || hasPermission('users', 'read'),
    },
    {
      title: 'Roles',
      url: '/dashboard/roles',
      icon: IconShield,
      visible: isAdmin.value,
    },
    {
      title: 'Permissions',
      url: '/dashboard/permissions',
      icon: IconLock,
      visible: isAdmin.value,
    },
    {
      title: 'Posts',
      url: '/dashboard/posts',
      icon: IconFileDescription,
      visible: hasPermission('posts', 'read') || isAdmin.value,
    },
    {
      title: 'OrderBook',
      url: '/dashboard/orderbook',
      icon: IconChartCandle,
      visible: true,
    },
  ]
  return items.filter(item => item.visible)
})

function navigate(item: { url: string; title: string }) {
  const isDashboard = item.url === '/dashboard'
  if (authStore.needsOnboarding && !isDashboard) {
    toast.info('Complete your onboarding first', {
      description: 'You need to finish setting up your profile to access this section.',
    })
    return
  }
  router.push(item.url)
}
</script>

<template>
  <SidebarGroup>
    <SidebarGroupContent class="flex flex-col gap-2">
      <SidebarMenu>
        <SidebarMenuItem v-for="item in navItems" :key="item.title">
          <SidebarMenuButton
            :tooltip="item.title"
            :class="{ 'opacity-50 cursor-not-allowed': authStore.needsOnboarding && item.url !== '/dashboard' }"
            @click="navigate(item)"
          >
            <component :is="item.icon" v-if="item.icon" />
            <span>{{ item.title }}</span>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>
    </SidebarGroupContent>
  </SidebarGroup>
</template>

// apps/web/src/components/nav-main.tsx
"use client"

import * as React from "react"
import Link from "next/link"
import { ChevronRightIcon, MailIcon, PlusCircleIcon, type LucideIcon } from "lucide-react"

import { Button } from "@/components/ui/button"
import {
  SidebarGroup,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
} from "@/components/ui/sidebar"
import { cn } from "@/lib/utils"
import { toast } from "sonner"

type NavItem = {
  title: string
  url: string
  icon?: LucideIcon
  items?: {
    title: string
    url: string
  }[]
}

export function NavMain({
  items,
  showQuickCreate = true,
  disabled = false,
}: {
  items: NavItem[]
  showQuickCreate?: boolean
  disabled?: boolean
}) {
  const [openMenus, setOpenMenus] = React.useState<Record<string, boolean>>({})

  const toggleMenu = (title: string) => {
    setOpenMenus((prev) => ({
      ...prev,
      [title]: !prev[title],
    }))
  }

  return (
    <SidebarGroup>
      <SidebarGroupContent className="flex flex-col gap-2">
        {showQuickCreate && (
          <SidebarMenu>
            <SidebarMenuItem className="flex items-center gap-2">
              <SidebarMenuButton
                tooltip="Quick Create"
                className="min-w-8 bg-primary text-primary-foreground duration-200 ease-linear hover:bg-primary/90 hover:text-primary-foreground active:bg-primary/90 active:text-primary-foreground"
              >
                <PlusCircleIcon />
                <span>Quick Create</span>
              </SidebarMenuButton>
              <Button
                size="icon"
                className="h-9 w-9 shrink-0 group-data-[collapsible=icon]:opacity-0"
                variant="outline"
              >
                <MailIcon />
                <span className="sr-only">Inbox</span>
              </Button>
            </SidebarMenuItem>
          </SidebarMenu>
        )}
        <SidebarMenu>
          {items.map((item) => {
            const isDashboard = item.url === "/dashboard"
            const isDisabled = disabled && !isDashboard

            const handleDisabledClick = (e: React.MouseEvent) => {
              e.preventDefault()
              toast.info("Complete your onboarding first", {
                description: "You need to finish setting up your profile to access this section.",
              })
            }

            return (
              <SidebarMenuItem key={item.title}>
                {item.items && item.items.length > 0 ? (
                  // Item avec sous-menu
                  <>
                    <SidebarMenuButton
                      tooltip={item.title}
                      onClick={isDisabled ? handleDisabledClick : () => toggleMenu(item.title)}
                      className={cn(isDisabled && "opacity-50 cursor-not-allowed")}
                    >
                      {item.icon && <item.icon />}
                      <span>{item.title}</span>
                      <ChevronRightIcon
                        className={cn(
                          "ml-auto size-4 transition-transform",
                          openMenus[item.title] && "rotate-90"
                        )}
                      />
                    </SidebarMenuButton>
                    {!isDisabled && openMenus[item.title] && (
                      <SidebarMenuSub>
                        {item.items.map((subItem) => (
                          <SidebarMenuSubItem key={subItem.title}>
                            <SidebarMenuSubButton asChild>
                              <Link href={subItem.url as any}>
                                <span>{subItem.title}</span>
                              </Link>
                            </SidebarMenuSubButton>
                          </SidebarMenuSubItem>
                        ))}
                      </SidebarMenuSub>
                    )}
                  </>
                ) : isDisabled ? (
                  // Item disabled - no link
                  <SidebarMenuButton
                    tooltip={item.title}
                    onClick={handleDisabledClick}
                    className="opacity-50 cursor-not-allowed"
                  >
                    {item.icon && <item.icon />}
                    <span>{item.title}</span>
                  </SidebarMenuButton>
                ) : (
                  // Item sans sous-menu - lien direct
                  <SidebarMenuButton tooltip={item.title} asChild>
                    <Link href={item.url as any}>
                      {item.icon && <item.icon />}
                      <span>{item.title}</span>
                    </Link>
                  </SidebarMenuButton>
                )}
              </SidebarMenuItem>
            )
          })}
        </SidebarMenu>
      </SidebarGroupContent>
    </SidebarGroup>
  )
}
