// apps/web-vuejs/src/components/onboarding/PersonalInfoForm.vue
<script setup lang="ts">
import { reactive, watch } from 'vue'
import type { PersonalInfoData } from '@rbac/types'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'

const props = defineProps<{
  modelValue?: PersonalInfoData
  isSubmitting: boolean
}>()

const emit = defineEmits<{
  submit: [data: PersonalInfoData]
}>()

const form = reactive<PersonalInfoData>({
  phone: '',
  date_of_birth: '',
  street: '',
  city: '',
  postal_code: '',
  country: '',
  nationality: '',
})

const errors = reactive<Partial<Record<keyof PersonalInfoData, string>>>({})


// Initialize form with existing data
watch(
  () => props.modelValue,
  (val) => {
    if (val) {
      Object.assign(form, val)
    }
  },
  { immediate: true },
)

const countries = [
  { value: 'FR', label: 'France' },
  { value: 'US', label: 'United States' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'DE', label: 'Germany' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'BE', label: 'Belgium' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'ES', label: 'Spain' },
  { value: 'IT', label: 'Italy' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'PT', label: 'Portugal' },
  { value: 'CA', label: 'Canada' },
  { value: 'JP', label: 'Japan' },
  { value: 'AU', label: 'Australia' },
]

function validate(): boolean {
  // Reset errors
  Object.keys(errors).forEach((key) => {
    delete errors[key as keyof PersonalInfoData]
  })

  let valid = true

  if (!form.phone.trim()) {
    errors.phone = 'Phone number is required'
    valid = false
  }
  if (!form.date_of_birth) {
    errors.date_of_birth = 'Date of birth is required'
    valid = false
  }
  if (!form.street.trim()) {
    errors.street = 'Street address is required'
    valid = false
  }
  if (!form.city.trim()) {
    errors.city = 'City is required'
    valid = false
  }
  if (!form.postal_code.trim()) {
    errors.postal_code = 'Postal code is required'
    valid = false
  }
  if (!form.country) {
    errors.country = 'Country is required'
    valid = false
  }
  if (!form.nationality) {
    errors.nationality = 'Nationality is required'
    valid = false
  }

  return valid
}

function handleSubmit() {
  if (validate()) {
    emit('submit', { ...form })
  }
}
</script>

<template>
  <form class="space-y-6" @submit.prevent="handleSubmit">
    <div class="grid gap-4 sm:grid-cols-2">
      <div class="flex flex-col gap-2">
        <Label for="phone">Phone number</Label>
        <Input
          id="phone"
          v-model="form.phone"
          type="tel"
          placeholder="+33 6 12 34 56 78"
        />
        <p v-if="errors.phone" class="text-destructive text-sm">{{ errors.phone }}</p>
      </div>

      <div class="flex flex-col gap-2">
        <Label for="date_of_birth">Date of birth</Label>
        <Input
          id="date_of_birth"
          v-model="form.date_of_birth"
          type="date"
        />
        <p v-if="errors.date_of_birth" class="text-destructive text-sm">{{ errors.date_of_birth }}</p>
      </div>
    </div>

    <div class="flex flex-col gap-2">
      <Label for="street">Street address</Label>
      <Input
        id="street"
        v-model="form.street"
        placeholder="123 Main Street"
      />
      <p v-if="errors.street" class="text-destructive text-sm">{{ errors.street }}</p>
    </div>

    <div class="grid gap-4 sm:grid-cols-3">
      <div class="flex flex-col gap-2">
        <Label for="city">City</Label>
        <Input
          id="city"
          v-model="form.city"
          placeholder="Paris"
        />
        <p v-if="errors.city" class="text-destructive text-sm">{{ errors.city }}</p>
      </div>

      <div class="flex flex-col gap-2">
        <Label for="postal_code">Postal code</Label>
        <Input
          id="postal_code"
          v-model="form.postal_code"
          placeholder="75001"
        />
        <p v-if="errors.postal_code" class="text-destructive text-sm">{{ errors.postal_code }}</p>
      </div>

      <div class="flex flex-col gap-2">
        <Label for="country">Country</Label>
        <Select v-model="form.country">
          <SelectTrigger>
            <SelectValue placeholder="Select country" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectItem
                v-for="c in countries"
                :key="c.value"
                :value="c.value"
              >
                {{ c.label }}
              </SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
        <p v-if="errors.country" class="text-destructive text-sm">{{ errors.country }}</p>
      </div>
    </div>

    <div class="flex flex-col gap-2">
      <Label for="nationality">Nationality</Label>
      <Select v-model="form.nationality">
        <SelectTrigger>
          <SelectValue placeholder="Select nationality" />
        </SelectTrigger>
        <SelectContent>
          <SelectGroup>
            <SelectItem
              v-for="c in countries"
              :key="c.value"
              :value="c.value"
            >
              {{ c.label }}
            </SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>
      <p v-if="errors.nationality" class="text-destructive text-sm">{{ errors.nationality }}</p>
    </div>

    <div class="flex justify-end pt-4">
      <Button type="submit" :disabled="isSubmitting">
        <span v-if="!isSubmitting">Continue</span>
        <span v-else>Saving...</span>
      </Button>
    </div>
  </form>
</template>

// apps/web/src/components/onboarding/steps/personal-info-form.tsx
'use client';

import { useState } from 'react';
import type { PersonalInfoData } from '@rbac/types';
import { personalInfoSchema } from '@/lib/validations/onboarding';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  ArrowRightIcon,
  LoaderIcon,
  PhoneIcon,
  CalendarIcon,
  MapPinIcon,
} from 'lucide-react';

const COUNTRIES = [
  { value: 'FR', label: 'France' },
  { value: 'DE', label: 'Germany' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'US', label: 'United States' },
  { value: 'CA', label: 'Canada' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'BE', label: 'Belgium' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'ES', label: 'Spain' },
  { value: 'IT', label: 'Italy' },
  { value: 'PT', label: 'Portugal' },
  { value: 'AT', label: 'Austria' },
  { value: 'IE', label: 'Ireland' },
  { value: 'SE', label: 'Sweden' },
  { value: 'NO', label: 'Norway' },
  { value: 'DK', label: 'Denmark' },
  { value: 'FI', label: 'Finland' },
  { value: 'JP', label: 'Japan' },
  { value: 'AU', label: 'Australia' },
  { value: 'SG', label: 'Singapore' },
  { value: 'HK', label: 'Hong Kong' },
] as const;

interface PersonalInfoFormProps {
  defaultValues?: PersonalInfoData;
  onSubmit: (data: PersonalInfoData) => void;
  isSubmitting: boolean;
}

export function PersonalInfoForm({
  defaultValues,
  onSubmit,
  isSubmitting,
}: PersonalInfoFormProps) {
  const [phone, setPhone] = useState(defaultValues?.phone ?? '');
  const [dateOfBirth, setDateOfBirth] = useState(
    defaultValues?.date_of_birth ?? ''
  );
  const [street, setStreet] = useState(defaultValues?.street ?? '');
  const [city, setCity] = useState(defaultValues?.city ?? '');
  const [postalCode, setPostalCode] = useState(
    defaultValues?.postal_code ?? ''
  );
  const [country, setCountry] = useState(defaultValues?.country ?? '');
  const [nationality, setNationality] = useState(
    defaultValues?.nationality ?? ''
  );
  const [errors, setErrors] = useState<Record<string, string>>({});

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setErrors({});

    const data: PersonalInfoData = {
      phone,
      date_of_birth: dateOfBirth,
      street,
      city,
      postal_code: postalCode,
      country,
      nationality,
    };

    const result = personalInfoSchema.safeParse(data);

    if (!result.success) {
      const fieldErrors: Record<string, string> = {};
      for (const issue of result.error.issues) {
        const field = issue.path[0] as string;
        if (!fieldErrors[field]) {
          fieldErrors[field] = issue.message;
        }
      }
      setErrors(fieldErrors);
      return;
    }

    onSubmit(result.data);
  };

  return (
    <Card className="relative overflow-hidden">
      <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-violet-600 via-indigo-600 to-violet-600" />

      <CardHeader className="pb-4">
        <CardTitle className="text-lg">Personal Information</CardTitle>
        <CardDescription>
          Please provide your personal details. This information is required for
          identity verification.
        </CardDescription>
      </CardHeader>

      <form onSubmit={handleSubmit}>
        <CardContent className="space-y-4">
          {/* Phone */}
          <div className="space-y-2">
            <Label htmlFor="phone" className="text-sm font-medium">
              Phone Number
            </Label>
            <div className="relative">
              <PhoneIcon className="absolute left-3 top-3 h-4 w-4 text-muted-foreground pointer-events-none" />
              <Input
                id="phone"
                type="tel"
                placeholder="+33 6 12 34 56 78"
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                className={`pl-10 h-11 ${errors.phone ? 'border-red-500 focus-visible:ring-red-500' : ''}`}
              />
            </div>
            {errors.phone && (
              <p className="text-xs text-red-600">{errors.phone}</p>
            )}
          </div>

          {/* Date of birth */}
          <div className="space-y-2">
            <Label htmlFor="date_of_birth" className="text-sm font-medium">
              Date of Birth
            </Label>
            <div className="relative">
              <CalendarIcon className="absolute left-3 top-3 h-4 w-4 text-muted-foreground pointer-events-none" />
              <Input
                id="date_of_birth"
                type="date"
                value={dateOfBirth}
                onChange={(e) => setDateOfBirth(e.target.value)}
                className={`pl-10 h-11 ${errors.date_of_birth ? 'border-red-500 focus-visible:ring-red-500' : ''}`}
              />
            </div>
            {errors.date_of_birth && (
              <p className="text-xs text-red-600">{errors.date_of_birth}</p>
            )}
          </div>

          {/* Street */}
          <div className="space-y-2">
            <Label htmlFor="street" className="text-sm font-medium">
              Street Address
            </Label>
            <div className="relative">
              <MapPinIcon className="absolute left-3 top-3 h-4 w-4 text-muted-foreground pointer-events-none" />
              <Input
                id="street"
                type="text"
                placeholder="123 Main Street"
                value={street}
                onChange={(e) => setStreet(e.target.value)}
                className={`pl-10 h-11 ${errors.street ? 'border-red-500 focus-visible:ring-red-500' : ''}`}
              />
            </div>
            {errors.street && (
              <p className="text-xs text-red-600">{errors.street}</p>
            )}
          </div>

          {/* City + Postal Code */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="city" className="text-sm font-medium">
                City
              </Label>
              <Input
                id="city"
                type="text"
                placeholder="Paris"
                value={city}
                onChange={(e) => setCity(e.target.value)}
                className={`h-11 ${errors.city ? 'border-red-500 focus-visible:ring-red-500' : ''}`}
              />
              {errors.city && (
                <p className="text-xs text-red-600">{errors.city}</p>
              )}
            </div>
            <div className="space-y-2">
              <Label htmlFor="postal_code" className="text-sm font-medium">
                Postal Code
              </Label>
              <Input
                id="postal_code"
                type="text"
                placeholder="75001"
                value={postalCode}
                onChange={(e) => setPostalCode(e.target.value)}
                className={`h-11 ${errors.postal_code ? 'border-red-500 focus-visible:ring-red-500' : ''}`}
              />
              {errors.postal_code && (
                <p className="text-xs text-red-600">{errors.postal_code}</p>
              )}
            </div>
          </div>

          {/* Country */}
          <div className="space-y-2">
            <Label htmlFor="country" className="text-sm font-medium">
              Country
            </Label>
            <Select value={country} onValueChange={setCountry}>
              <SelectTrigger
                id="country"
                className={`h-11 ${errors.country ? 'border-red-500 focus-visible:ring-red-500' : ''}`}
              >
                <SelectValue placeholder="Select a country" />
              </SelectTrigger>
              <SelectContent>
                {COUNTRIES.map((c) => (
                  <SelectItem key={c.value} value={c.value}>
                    {c.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.country && (
              <p className="text-xs text-red-600">{errors.country}</p>
            )}
          </div>

          {/* Nationality */}
          <div className="space-y-2">
            <Label htmlFor="nationality" className="text-sm font-medium">
              Nationality
            </Label>
            <Select value={nationality} onValueChange={setNationality}>
              <SelectTrigger
                id="nationality"
                className={`h-11 ${errors.nationality ? 'border-red-500 focus-visible:ring-red-500' : ''}`}
              >
                <SelectValue placeholder="Select your nationality" />
              </SelectTrigger>
              <SelectContent>
                {COUNTRIES.map((c) => (
                  <SelectItem key={c.value} value={c.value}>
                    {c.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.nationality && (
              <p className="text-xs text-red-600">{errors.nationality}</p>
            )}
          </div>
        </CardContent>

        <CardFooter className="flex justify-end pt-2 pb-6">
          <Button
            type="submit"
            disabled={isSubmitting}
            className="bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-700 hover:to-indigo-700 text-white shadow-lg shadow-violet-500/25 group"
          >
            {isSubmitting ? (
              <>
                <LoaderIcon className="mr-2 h-4 w-4 animate-spin" />
                Saving...
              </>
            ) : (
              <>
                Continue
                <ArrowRightIcon className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
              </>
            )}
          </Button>
        </CardFooter>
      </form>
    </Card>
  );
}
